# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: YzU4OTA0YmRjM2I4ZTYxNDZhNzFiMWExNTNlYmY3MjA3ODIxYWM3OWQ3NmY2NjQ2OWJhMDMxZjM3ZjA4ZDM1ZjE1YmMyYjczYjM4ZThiYTI1MDcxZjRlYWJmOTdmNTFlNmJhYjYzY2NlZGZjNzg0MTI2MWRhMzY3ZDI4OGMxNDM=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
